policy:
  approval:
    - "approved by a write-permission holder"
approval_rules:
  - name: "approved by a write-permission holder"
    requires:
      count: 1
      permissions:
        - write
        - admin
    options:
      allow_author: true
      allow_contributor: true
      allow_non_author_contributor: true
      methods:
        github_review: true
