policy:
  approval:
    - "approved by a listed reviewer who is not a contributor"
approval_rules:
  - name: "approved by a listed reviewer who is not a contributor"
    requires:
      count: 1
      users:
        - "bobfortesting123-cloud"
    options:
      allow_author: false
      allow_contributor: false
      allow_non_author_contributor: false
      invalidate_on_push: false
      methods:
        github_review: true
